# Generated by Django 4.0.1 on 2022-09-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Choose User Type', 'Choose User Type'), ('Admin', 'Administrator'), ('BHW', 'Barangay Health Worker'), ('P/G', 'Parent/Guardian')], default='Choose User Type', max_length=100),
        ),
    ]
