# Generated by Django 4.0.1 on 2022-09-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0004_barangayhealthworker_parents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
