# Generated by Django 4.1.2 on 2022-10-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0006_parents_preschoolers'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayhealthworker',
            name='bhw_barangay',
            field=models.CharField(choices=[('Select Barangay', 'Select Barangay'), ('Burol', 'Burol'), ('Burol I', 'Burol I'), ('Burol II', 'Burol II'), ('Burol III', 'Burol III'), ('Datu Esmael', 'Datu Esmael'), ('Emmanuel Begado I', 'Emmanuel Begado I'), ('Emmanuel Begado II', 'Emmanuel Begado II')], default='Select Barangay', max_length=100),
        ),
    ]
