# Generated by Django 4.1.2 on 2022-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0008_rename_parents_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschooler',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preschooler',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preschooler',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preschooler',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preschooler',
            name='suffix_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
