# Generated by Django 4.1.2 on 2022-10-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0009_preschooler_birthday_preschooler_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preschooler',
        ),
    ]
