# Generated by Django 4.1.2 on 2022-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0012_customuser_middle_name_customuser_suffix_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschooler',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='preschooler',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
