# Generated by Django 4.1.2 on 2022-10-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0013_preschooler_height_preschooler_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
