# Generated by Django 4.1.2 on 2022-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0016_alter_preschooler_gender_alter_preschooler_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preschooler',
            name='date_measured',
            field=models.DateField(blank=True, null=True),
        ),
    ]
