# Generated by Django 4.1.2 on 2022-10-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0019_alter_customuser_suffix_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='suffix_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preschooler',
            name='suffix_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
