# Generated by Django 4.1.2 on 2022-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0020_alter_customuser_suffix_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_action', models.CharField(max_length=500, null=True)),
                ('logged_userid', models.IntegerField(null=True)),
                ('datetime_log', models.DateTimeField(null=True)),
            ],
        ),
    ]
