# Generated by Django 4.1.2 on 2022-11-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0024_alter_historicalpreschooler_health_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_name', models.CharField(choices=[('BCG', 'BCG'), ('Hepatitis B', 'Hepatitis B'), ('Oral Poliovirus Vaccine', 'Oral Poliovirus Vaccine'), ('Pentavalent Vaccine', 'Pentavalent Vaccine'), ('Measles Containing Vaccines', 'Measles Containing Vaccines'), ('Tetanus Toxoid', 'Tetanus Toxoid'), ('Inactivated Polio Vaccine', 'Inactivated Polio Vaccine'), ('Vax8', 'Vax8')], max_length=500)),
                ('vax_dose', models.IntegerField()),
                ('vax_date', models.DateField(blank=True, null=True)),
                ('vax_remarks', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
