# Generated by Django 4.1.2 on 2022-11-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0025_vaccine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
