# Generated by Django 4.1.2 on 2022-11-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0026_delete_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vax_name', models.CharField(choices=[('BCG', 'BCG'), ('Hepatitis B', 'Hepatitis B'), ('Oral Poliovirus Vaccine', 'Oral Poliovirus Vaccine'), ('Pentavalent Vaccine', 'Pentavalent Vaccine'), ('Measles Containing Vaccines', 'Measles Containing Vaccines'), ('Tetanus Toxoid', 'Tetanus Toxoid'), ('Inactivated Polio Vaccine', 'Inactivated Polio Vaccine'), ('Vax8', 'Vax8')], max_length=500)),
                ('vax_dose', models.IntegerField()),
                ('vax_date', models.DateField(blank=True, null=True)),
                ('vax_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('vax_preschooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilingApp.preschooler')),
            ],
        ),
    ]
