# Generated by Django 4.1.2 on 2022-11-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0028_alter_vaccine_vax_name_alter_vaccine_vax_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
