# Generated by Django 4.1.2 on 2022-11-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0031_barangay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preschooler',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='vax_preschooler',
        ),
        migrations.DeleteModel(
            name='HistoricalPreschooler',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Preschooler',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
