# Generated by Django 4.1.2 on 2022-11-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0033_parent_preschooler_vaccine_historicalpreschooler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarangayHealthWorker',
        ),
    ]
