# Generated by Django 4.1.2 on 2022-12-08 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0036_barangay_brgy_address_barangay_brgy_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreschoolerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(45.0), django.core.validators.MaxValueValidator(120.0)])),
                ('weight', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(28.0)])),
                ('date_measured', models.DateField(blank=True, null=True)),
                ('wfa', models.FloatField(blank=True, null=True)),
                ('hfa', models.FloatField(blank=True, null=True)),
                ('whfa', models.FloatField(blank=True, null=True)),
                ('id_preschooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilingApp.preschooler')),
            ],
        ),
    ]
