# Generated by Django 4.1.2 on 2023-01-05 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0038_remove_preschoolerhistory_hfa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreschooler',
            name='ps_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preschooler',
            name='ps_image',
            field=models.ImageField(blank=True, null=True, upload_to='ps_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Choose User Type', 'Choose User Type'), ('Admin', 'Administrator'), ('BHW', 'Barangay Health Worker'), ('P/G', 'Parent/Guardian')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='user_type',
            field=models.CharField(choices=[('Choose User Type', 'Choose User Type'), ('Admin', 'Administrator'), ('BHW', 'Barangay Health Worker'), ('P/G', 'Parent/Guardian')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpreschooler',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicalpreschooler',
            name='weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preschooler',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='preschooler',
            name='weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
