# Generated by Django 4.1.3 on 2023-01-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilingApp', '0039_historicalpreschooler_ps_image_preschooler_ps_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='preschooler',
            name='ps_image',
            field=models.ImageField(blank=True, null=True, upload_to='ps_images'),
        ),
    ]
